// can't use private fields, because Object Mapper can't access them
public class Patient {
	
	public String firstName;
	public String lastName;
	public String dob;
	public String condition;
	public String vitalSigns;
	public String treatment;
	
	// will have 0 or 1 (false/true)
	public int discharged;
	
	public int priority;
	
	//internal ID used to track patient in DB, generated by randomizer class
	public String intID;
	
	public Patient(String firstName, String lastName, String dob, String condition){
		this.firstName = firstName;
		this.lastName = lastName;
		this.dob = dob;
		this.condition = condition;
		this.discharged = 0;
		this.priority = 0;
		this.intID = firstName.substring(0, 1).toUpperCase()+lastName.substring(0, 1).toUpperCase()
				+Randomizer.generateRandomCh();
		
	}
	
	// constructor to create new patient getting all data from existing patient from SQL DB
	public Patient(String firstName, String lastName, String dob, String condition, String vital,
			String treat, int discharged, int priority, String intID){
		this.firstName = firstName;
		this.lastName = lastName;
		this.dob = dob;
		this.condition = condition;
		this.vitalSigns = vital;
		this.treatment = treat;
		this.discharged = discharged;
		this.priority = priority;
		this.intID = intID;
	}
	
	public int getPriority(){
		return this.priority;
	}
	
	public String toString(){
		return this.firstName + " " + this.lastName;
	}
	
	public String getIntID(){
		return this.intID;
	}
	// used to create patient with existing ID from DB ResultSet
	public void setIntID(String ID){
		this.intID = ID;
	}

}
